"""Dependency, lock, source, and metadata identity tests."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
import tomllib
import unittest

from quantitative_trading_research.config.environment_diagnostics import (
    build_dependency_metadata,
)
from quantitative_trading_research.config.settings import (
    build_accepted_settings,
)


ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = ROOT / "pyproject.toml"
LOCK = ROOT / "requirements.lock"
MANIFEST = (
    ROOT
    / "docs"
    / "reports"
    / "C3_environment_and_dependency_manifest.yaml"
)


class DependencyIdentityTests(unittest.TestCase):
    def test_pyproject_declares_exact_empty_project_dependency_set(self) -> None:
        data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))

        self.assertEqual(
            data["build-system"]["requires"],
            ["setuptools==83.0.0"],
        )
        self.assertEqual(
            data["build-system"]["build-backend"],
            "setuptools.build_meta",
        )
        self.assertEqual(
            data["project"]["name"],
            "quantitative-trading-research-platform",
        )
        self.assertEqual(data["project"]["version"], "0.0.0")
        self.assertEqual(
            data["project"]["requires-python"],
            ">=3.12,<3.13",
        )
        self.assertEqual(data["project"]["dependencies"], [])
        self.assertNotIn("optional-dependencies", data["project"])

    def test_dependency_metadata_is_zero_count_and_stable(self) -> None:
        settings = build_accepted_settings()
        payload, checksum, identity = build_dependency_metadata(settings)

        self.assertEqual(payload["direct_runtime_dependencies"], [])
        self.assertEqual(payload["direct_test_dependencies"], [])
        self.assertEqual(payload["resolved_project_dependencies"], [])
        self.assertEqual(payload["direct_project_dependency_count"], 0)
        self.assertEqual(payload["resolved_project_dependency_count"], 0)
        self.assertEqual(
            payload["build_system_requirements"],
            ["setuptools==83.0.0"],
        )
        self.assertRegex(checksum, r"^[0-9a-f]{64}$")
        self.assertTrue(identity.endswith(checksum))

    def test_lock_is_present_and_matches_empty_lock_contract(self) -> None:
        self.assertTrue(LOCK.is_file(), "requirements.lock is required")

        raw = LOCK.read_bytes()
        text = raw.decode("utf-8")

        self.assertTrue(raw.endswith(b"\n"))
        self.assertNotIn(b"\r", raw)
        self.assertTrue(text.startswith("#\n"))
        self.assertIn(
            "This file is autogenerated by pip-compile with Python 3.12",
            text,
        )
        self.assertIn("--generate-hashes", text)
        self.assertIn("--newline=LF", text)
        self.assertIn("--no-emit-find-links", text)
        self.assertIn("--no-emit-index-url", text)
        self.assertIn("--no-emit-options", text)
        self.assertIn("--no-emit-trusted-host", text)
        self.assertIn("--output-file=requirements.lock", text)
        self.assertIn("--strip-extras", text)
        self.assertIn("pyproject.toml", text)

        noncomment = [
            line.strip()
            for line in text.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
        self.assertEqual(noncomment, [])
        self.assertNotIn("--hash=", text)
        self.assertNotIn("--index-url", text)
        self.assertNotIn("--extra-index-url", text)
        self.assertNotIn("--trusted-host", text)
        self.assertNotIn("--find-links", text)
        self.assertNotIn("git+", text.lower())
        self.assertNotIn("hg+", text.lower())
        self.assertNotIn("svn+", text.lower())
        self.assertNotIn("bzr+", text.lower())
        self.assertNotIn("http://", text.lower())
        self.assertNotIn("https://", text.lower())
        self.assertNotIn("file://", text.lower())
        self.assertNotRegex(
            text,
            r"(?m)^[A-Za-z0-9_.-]+(?:\[.*\])?(?:==|>=|<=|~=|!=|>|<)",
        )

    def test_manifest_binds_lock_checksum_to_exact_bytes(self) -> None:
        manifest = MANIFEST.read_text(encoding="utf-8")
        raw = LOCK.read_bytes()
        checksum = hashlib.sha256(raw).hexdigest()

        match = re.search(
            r"(?m)^  canonical_checksum: ([0-9a-f]{64})$",
            manifest,
        )
        self.assertIsNotNone(
            match,
            "manifest canonical lock checksum remains unbound",
        )
        assert match is not None
        self.assertEqual(match.group(1), checksum)

    def test_manifest_records_exact_package_source_identities(self) -> None:
        manifest = MANIFEST.read_text(encoding="utf-8")

        self.assertIn(
            "allowlist_id: C3_DEPENDENCY_SOURCE_ALLOWLIST_V1",
            manifest,
        )
        self.assertIn(
            "normalized_url: https://pypi.org:443/simple/",
            manifest,
        )
        self.assertIn(
            "normalized_url: "
            "https://files.pythonhosted.org:443/packages/",
            manifest,
        )
        self.assertIn("credentials_permitted: false", manifest)

    def test_tooling_is_not_counted_as_project_dependency(self) -> None:
        data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
        manifest = MANIFEST.read_text(encoding="utf-8")

        self.assertEqual(data["project"]["dependencies"], [])
        self.assertIn("direct_project_dependency_count: 0", manifest)
        self.assertIn("resolved_project_dependency_count: 0", manifest)
        self.assertNotIn("pip==26.1.2", data["project"]["dependencies"])
        self.assertNotIn("pip-tools==7.6.0", data["project"]["dependencies"])
        self.assertNotIn("build==1.5.0", data["project"]["dependencies"])


if __name__ == "__main__":
    unittest.main()
